# =============================================================================
# Base Project Configuration
# =============================================================================
project:
  name: "AI-code-assistant"
  version: "0.1.0"
  description: "AI-powered coding assistant with multi-LLM support"

# =============================================================================
# File Paths
# =============================================================================
paths:
  data_raw: "./data/raw"
  data_processed: "./data/processed"
  model_checkpoints: "./models"
  logs: "./logs"
  static: "./static"
  templates: "./templates"

# =============================================================================
# Supported Programming Languages
# =============================================================================
languages:
  priority: ["python", "csharp", "c", "javascript", "typescript", "html", "css"]
  # Reference to quality standards file
  quality_standards_file: "./configs/quality_standards.yaml"
  
# =============================================================================
# Security Settings
# =============================================================================
security:
  allowed_hosts: ["localhost", "127.0.0.1"]
  cors_origins: ["http://localhost:3000", "http://localhost:8000"]
  max_request_size: 10485760  # 10MB

# =============================================================================
# Logging Configuration
# =============================================================================
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/app.log"
  max_size: "10MB"
  backup_count: 5