# =============================================================================
# Base Project Configuration
# =============================================================================
project:
  name: "AI-code-assistant"
  version: "0.1.0"
  description: "AI-powered coding assistant with multi-LLM support"

# =============================================================================
# File Paths
# =============================================================================
paths:
  data_raw: "./data/raw"
  data_processed: "./data/processed"
  model_checkpoints: "./models"
  logs: "./logs"
  static: "./static"
  templates: "./templates"

# =============================================================================
# Supported Programming Languages
# =============================================================================
languages:
  # Reference to languages configuration file
  config_file: "./configs/languages.yaml"
  # Reference to quality standards file
  quality_standards_file: "./configs/quality_standards.yaml"
  
# =============================================================================
# Security Configuration Reference
# =============================================================================
security:
  # Reference to security configuration file
  config_file: "./configs/security.yaml"
  
# =============================================================================
# Database Configuration Reference
# =============================================================================
database:
  # Reference to database configuration file
  config_file: "./configs/database.yaml"
  
# =============================================================================
# Integration Configuration Reference
# =============================================================================
integration:
  # Reference to integration configuration file
  config_file: "./configs/integration.yaml"
  
# =============================================================================
# Model Configuration Reference
# =============================================================================
models:
  # Reference to model configuration file
  config_file: "./configs/model.yaml"
  
# =============================================================================
# API Settings
# =============================================================================
api:
  # Default timeout in seconds for API requests
  default_timeout: 30
  # Maximum timeout in seconds
  max_timeout: 120
  # Timeout for analysis requests (typically longer)
  analysis_timeout: 60

# =============================================================================
# Logging Configuration
# =============================================================================
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "./logs/app.log"
  max_size: "10MB"
  backup_count: 5