project:
  name: "AI-code-assistant"
  version: "0.0.1"
  
paths:
  data_raw: "./data/raw"
  data_processed: "./data/processed"
  model_checkpoints: "./models"
  
languages:
  priority: ["python", "csharp", "c", "javascript", "typescript", "html", "css"]
  
quality_standards:
  min_complexity: 0.4  # 0-1 scale
  required_keys: ["answer", "explanation"]  # For structured responses
  banned_patterns:
    - "eval("
    - "system("
    - "os.popen"